### PR TITLE
Changes to estimateCellCounts

### PR DESCRIPTION
**Pull request by sandrews5**
1) Get platform from user rgSet instead of have it hard coded
2) Fix bug when combining user and reference rgSets
3) Implement cord blood estimation
4) Update man file to reflect cord blood changes and document frontal cortex estimation

### CODE REVIEW

**Comment by kasperdanielhansen** [comment]
There are many changes, it would have been easier to consider multiple pull requests.
This line
```
compositeCellType <- match.arg(compositeCellType,c("Blood","CordBlood","DLPFC"))
```
hardcodes the set of reference data.  I don't like that.

For the main methodological changes, not having an equal number of up and down, I want this to be an argument to the function, perhaps accepting values like "yes", "no", "auto" where "auto" would pick the best choice according to you (like it does right now).

Finally, I think we need to be able to specific the preprocessing used; you seem (?) to have changed the preprocessing method.

**Comment by sandrews5** [comment]
1) Okay, will remove. Actually in hindsight much of the benefit of this line can be dealt with via the error message that prints if a reference package doesn't exist.

2) Just to clarify, this is what I'm envisioning, how does this sound? We can have an argument called probeSelection that can take 3 values:

- "both": takes an equal number up and down
-"any": takes the specified number in any direction
-"auto": this will coerce to "both" when compositeCellType is brain or blood and "any" when it is cord blood.
Default would be "auto". Also, is it necessary to make the number of probes selected a user option? What should we do in the case where the function can't find the specified number of probes (however it was told to find them)?

3) So right now it does noob for cord blood but quantile for anything else. Again, just clarify, do you want the user to be able to choose this though? We chose noob for cord blood because we saw that the overall distribution of of one of the cell types (nRBCs) was quite different from the rest. But we could set up argument (say "processingMethod") with a similar structure to 2) where we provide an "auto" approach as default (quantile for blood and brain; noob for cord blood) but allow for user specification also.

**Comment by kasperdanielhansen** [comment]
2) This is exactly what I meant.
3) again, this sounds good.

In my understanding, at least for the present version of the method, these two choices have not been subjected to detailed evaluation.  It is entirely possible that the best answer to (2) is to always be "any" and that the best answer to (3) is noob.  By exposing the selection of these things we make it possible for users to play a bit.  I am all for locking down user arguments to functions (indeed, I would consider it a weakness to have too many options in general), but I would also to some extent like this to be the result of experiments.  What I think is clearly wrong is to not expose the option and then have dataset dependent choices.  What would happen if a new dataset (either new tissue or new dataset for existing tissue) comes along?  Not sure we want to expose everything of course, but in this case your experience clearly suggests that the best choice is dataset dependent.  Then I think we need to expose the argument.

**Comment by sandrews5** [comment]
1) Added 'processMethod' argument: users can choose any of the preprocess functions manually ("Funnorm","Illumina","Noob","Quantile", or "SWAN") or leave the default "auto", which picks noob for cord blood and quantile otherwise. 
2) Added "probeSelect" argument which lets users manually choose to take 50 probes from hyper and hypo methylated sides ("both") or to take the top 100 regardless of direction of effect ("any"). Default chooses "any" for cord blood and "both" for anything else.

**Pull request merged**
